/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TRightQuote extends Token
{
    public TRightQuote()
    {
        super.setText("”");
    }

    public TRightQuote(int line, int pos)
    {
        super.setText("”");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRightQuote(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRightQuote(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRightQuote text.");
    }
}
