/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class AArrayType extends PType
{
    private TInt _int_;
    private PInttype _inttype_;

    public AArrayType()
    {
        // Constructor
    }

    public AArrayType(
        @SuppressWarnings("hiding") TInt _int_,
        @SuppressWarnings("hiding") PInttype _inttype_)
    {
        // Constructor
        setInt(_int_);

        setInttype(_inttype_);

    }

    @Override
    public Object clone()
    {
        return new AArrayType(
            cloneNode(this._int_),
            cloneNode(this._inttype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayType(this);
    }

    public TInt getInt()
    {
        return this._int_;
    }

    public void setInt(TInt node)
    {
        if(this._int_ != null)
        {
            this._int_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._int_ = node;
    }

    public PInttype getInttype()
    {
        return this._inttype_;
    }

    public void setInttype(PInttype node)
    {
        if(this._inttype_ != null)
        {
            this._inttype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inttype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._int_)
            + toString(this._inttype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._int_ == child)
        {
            this._int_ = null;
            return;
        }

        if(this._inttype_ == child)
        {
            this._inttype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._int_ == oldChild)
        {
            setInt((TInt) newChild);
            return;
        }

        if(this._inttype_ == oldChild)
        {
            setInttype((PInttype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
