/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class ALess extends PLess
{
    private PTerm _term_;
    private PLlist _llist_;

    public ALess()
    {
        // Constructor
    }

    public ALess(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") PLlist _llist_)
    {
        // Constructor
        setTerm(_term_);

        setLlist(_llist_);

    }

    @Override
    public Object clone()
    {
        return new ALess(
            cloneNode(this._term_),
            cloneNode(this._llist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALess(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public PLlist getLlist()
    {
        return this._llist_;
    }

    public void setLlist(PLlist node)
    {
        if(this._llist_ != null)
        {
            this._llist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._llist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._llist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._llist_ == child)
        {
            this._llist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._llist_ == oldChild)
        {
            setLlist((PLlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
