/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class AMultTlist extends PTlist
{
    private TMult _mult_;
    private PNotNonterminal _notNonterminal_;
    private PTlist _tlist_;

    public AMultTlist()
    {
        // Constructor
    }

    public AMultTlist(
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PNotNonterminal _notNonterminal_,
        @SuppressWarnings("hiding") PTlist _tlist_)
    {
        // Constructor
        setMult(_mult_);

        setNotNonterminal(_notNonterminal_);

        setTlist(_tlist_);

    }

    @Override
    public Object clone()
    {
        return new AMultTlist(
            cloneNode(this._mult_),
            cloneNode(this._notNonterminal_),
            cloneNode(this._tlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultTlist(this);
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PNotNonterminal getNotNonterminal()
    {
        return this._notNonterminal_;
    }

    public void setNotNonterminal(PNotNonterminal node)
    {
        if(this._notNonterminal_ != null)
        {
            this._notNonterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notNonterminal_ = node;
    }

    public PTlist getTlist()
    {
        return this._tlist_;
    }

    public void setTlist(PTlist node)
    {
        if(this._tlist_ != null)
        {
            this._tlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mult_)
            + toString(this._notNonterminal_)
            + toString(this._tlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._notNonterminal_ == child)
        {
            this._notNonterminal_ = null;
            return;
        }

        if(this._tlist_ == child)
        {
            this._tlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._notNonterminal_ == oldChild)
        {
            setNotNonterminal((PNotNonterminal) newChild);
            return;
        }

        if(this._tlist_ == oldChild)
        {
            setTlist((PTlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
