/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class ANewFactor extends PFactor
{
    private TNew _new_;
    private PNewNonterminal _newNonterminal_;

    public ANewFactor()
    {
        // Constructor
    }

    public ANewFactor(
        @SuppressWarnings("hiding") TNew _new_,
        @SuppressWarnings("hiding") PNewNonterminal _newNonterminal_)
    {
        // Constructor
        setNew(_new_);

        setNewNonterminal(_newNonterminal_);

    }

    @Override
    public Object clone()
    {
        return new ANewFactor(
            cloneNode(this._new_),
            cloneNode(this._newNonterminal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewFactor(this);
    }

    public TNew getNew()
    {
        return this._new_;
    }

    public void setNew(TNew node)
    {
        if(this._new_ != null)
        {
            this._new_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._new_ = node;
    }

    public PNewNonterminal getNewNonterminal()
    {
        return this._newNonterminal_;
    }

    public void setNewNonterminal(PNewNonterminal node)
    {
        if(this._newNonterminal_ != null)
        {
            this._newNonterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newNonterminal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._new_)
            + toString(this._newNonterminal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._new_ == child)
        {
            this._new_ = null;
            return;
        }

        if(this._newNonterminal_ == child)
        {
            this._newNonterminal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._new_ == oldChild)
        {
            setNew((TNew) newChild);
            return;
        }

        if(this._newNonterminal_ == oldChild)
        {
            setNewNonterminal((PNewNonterminal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
