/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class ANotNotterminal extends PNotterminal
{
    private TNot _not_;
    private PNotterminal _notterminal_;

    public ANotNotterminal()
    {
        // Constructor
    }

    public ANotNotterminal(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PNotterminal _notterminal_)
    {
        // Constructor
        setNot(_not_);

        setNotterminal(_notterminal_);

    }

    @Override
    public Object clone()
    {
        return new ANotNotterminal(
            cloneNode(this._not_),
            cloneNode(this._notterminal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNotterminal(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PNotterminal getNotterminal()
    {
        return this._notterminal_;
    }

    public void setNotterminal(PNotterminal node)
    {
        if(this._notterminal_ != null)
        {
            this._notterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notterminal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._notterminal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._notterminal_ == child)
        {
            this._notterminal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._notterminal_ == oldChild)
        {
            setNotterminal((PNotterminal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
