/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class APlusLlist extends PLlist
{
    private TPlus _plus_;
    private PTerm _term_;
    private PLlist _llist_;

    public APlusLlist()
    {
        // Constructor
    }

    public APlusLlist(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") PLlist _llist_)
    {
        // Constructor
        setPlus(_plus_);

        setTerm(_term_);

        setLlist(_llist_);

    }

    @Override
    public Object clone()
    {
        return new APlusLlist(
            cloneNode(this._plus_),
            cloneNode(this._term_),
            cloneNode(this._llist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusLlist(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public PLlist getLlist()
    {
        return this._llist_;
    }

    public void setLlist(PLlist node)
    {
        if(this._llist_ != null)
        {
            this._llist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._llist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._term_)
            + toString(this._llist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._llist_ == child)
        {
            this._llist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._llist_ == oldChild)
        {
            setLlist((PLlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
