/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TPrintln extends Token
{
    public TPrintln()
    {
        super.setText("System.out.println");
    }

    public TPrintln(int line, int pos)
    {
        super.setText("System.out.println");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrintln(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrintln(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrintln text.");
    }
}
