/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class AExp extends PExp
{
    private PAndNonterminal _andNonterminal_;
    private PElist _elist_;

    public AExp()
    {
        // Constructor
    }

    public AExp(
        @SuppressWarnings("hiding") PAndNonterminal _andNonterminal_,
        @SuppressWarnings("hiding") PElist _elist_)
    {
        // Constructor
        setAndNonterminal(_andNonterminal_);

        setElist(_elist_);

    }

    @Override
    public Object clone()
    {
        return new AExp(
            cloneNode(this._andNonterminal_),
            cloneNode(this._elist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp(this);
    }

    public PAndNonterminal getAndNonterminal()
    {
        return this._andNonterminal_;
    }

    public void setAndNonterminal(PAndNonterminal node)
    {
        if(this._andNonterminal_ != null)
        {
            this._andNonterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andNonterminal_ = node;
    }

    public PElist getElist()
    {
        return this._elist_;
    }

    public void setElist(PElist node)
    {
        if(this._elist_ != null)
        {
            this._elist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andNonterminal_)
            + toString(this._elist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andNonterminal_ == child)
        {
            this._andNonterminal_ = null;
            return;
        }

        if(this._elist_ == child)
        {
            this._elist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andNonterminal_ == oldChild)
        {
            setAndNonterminal((PAndNonterminal) newChild);
            return;
        }

        if(this._elist_ == oldChild)
        {
            setElist((PElist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
