/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import java.util.*;
import lexing.analysis.*;

@SuppressWarnings("nls")
public final class AFormalvarexpStatement extends PStatement
{
    private TLeftParen _leftParen_;
    private PType _type_;
    private TIdentifier _identifier_;
    private PAssignNonterminal _assignNonterminal_;
    private TRightParen _rightParen_;
    private final LinkedList<PFormalvarexp> _formalvarexp_ = new LinkedList<PFormalvarexp>();
    private TSemi _semi_;

    public AFormalvarexpStatement()
    {
        // Constructor
    }

    public AFormalvarexpStatement(
        @SuppressWarnings("hiding") TLeftParen _leftParen_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PAssignNonterminal _assignNonterminal_,
        @SuppressWarnings("hiding") TRightParen _rightParen_,
        @SuppressWarnings("hiding") List<PFormalvarexp> _formalvarexp_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setLeftParen(_leftParen_);

        setType(_type_);

        setIdentifier(_identifier_);

        setAssignNonterminal(_assignNonterminal_);

        setRightParen(_rightParen_);

        setFormalvarexp(_formalvarexp_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AFormalvarexpStatement(
            cloneNode(this._leftParen_),
            cloneNode(this._type_),
            cloneNode(this._identifier_),
            cloneNode(this._assignNonterminal_),
            cloneNode(this._rightParen_),
            cloneList(this._formalvarexp_),
            cloneNode(this._semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormalvarexpStatement(this);
    }

    public TLeftParen getLeftParen()
    {
        return this._leftParen_;
    }

    public void setLeftParen(TLeftParen node)
    {
        if(this._leftParen_ != null)
        {
            this._leftParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftParen_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PAssignNonterminal getAssignNonterminal()
    {
        return this._assignNonterminal_;
    }

    public void setAssignNonterminal(PAssignNonterminal node)
    {
        if(this._assignNonterminal_ != null)
        {
            this._assignNonterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignNonterminal_ = node;
    }

    public TRightParen getRightParen()
    {
        return this._rightParen_;
    }

    public void setRightParen(TRightParen node)
    {
        if(this._rightParen_ != null)
        {
            this._rightParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightParen_ = node;
    }

    public LinkedList<PFormalvarexp> getFormalvarexp()
    {
        return this._formalvarexp_;
    }

    public void setFormalvarexp(List<PFormalvarexp> list)
    {
        this._formalvarexp_.clear();
        this._formalvarexp_.addAll(list);
        for(PFormalvarexp e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leftParen_)
            + toString(this._type_)
            + toString(this._identifier_)
            + toString(this._assignNonterminal_)
            + toString(this._rightParen_)
            + toString(this._formalvarexp_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leftParen_ == child)
        {
            this._leftParen_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._assignNonterminal_ == child)
        {
            this._assignNonterminal_ = null;
            return;
        }

        if(this._rightParen_ == child)
        {
            this._rightParen_ = null;
            return;
        }

        if(this._formalvarexp_.remove(child))
        {
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leftParen_ == oldChild)
        {
            setLeftParen((TLeftParen) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._assignNonterminal_ == oldChild)
        {
            setAssignNonterminal((PAssignNonterminal) newChild);
            return;
        }

        if(this._rightParen_ == oldChild)
        {
            setRightParen((TRightParen) newChild);
            return;
        }

        for(ListIterator<PFormalvarexp> i = this._formalvarexp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFormalvarexp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
