/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class ANotNotNonterminal extends PNotNonterminal
{
    private TNot _not_;
    private PNotNonterminal _notNonterminal_;

    public ANotNotNonterminal()
    {
        // Constructor
    }

    public ANotNotNonterminal(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PNotNonterminal _notNonterminal_)
    {
        // Constructor
        setNot(_not_);

        setNotNonterminal(_notNonterminal_);

    }

    @Override
    public Object clone()
    {
        return new ANotNotNonterminal(
            cloneNode(this._not_),
            cloneNode(this._notNonterminal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNotNonterminal(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PNotNonterminal getNotNonterminal()
    {
        return this._notNonterminal_;
    }

    public void setNotNonterminal(PNotNonterminal node)
    {
        if(this._notNonterminal_ != null)
        {
            this._notNonterminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notNonterminal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._notNonterminal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._notNonterminal_ == child)
        {
            this._notNonterminal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._notNonterminal_ == oldChild)
        {
            setNotNonterminal((PNotNonterminal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
