/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.analysis;

import lexing.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTDoubleSlashComment(TDoubleSlashComment node);
    void caseTSpace(TSpace node);
    void caseTClas(TClas node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTMain(TMain node);
    void caseTString(TString node);
    void caseTExtends(TExtends node);
    void caseTReturn(TReturn node);
    void caseTInt(TInt node);
    void caseTBoolean(TBoolean node);
    void caseTIf(TIf node);
    void caseTDo(TDo node);
    void caseTWhile(TWhile node);
    void caseTFor(TFor node);
    void caseTSwitch(TSwitch node);
    void caseTElse(TElse node);
    void caseTCase(TCase node);
    void caseTDefault(TDefault node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTNew(TNew node);
    void caseTThis(TThis node);
    void caseTAssign(TAssign node);
    void caseTCompare(TCompare node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDivide(TDivide node);
    void caseTMod(TMod node);
    void caseTLeftParen(TLeftParen node);
    void caseTRightParen(TRightParen node);
    void caseTLeftBracket(TLeftBracket node);
    void caseTRightBracket(TRightBracket node);
    void caseTLeftBrace(TLeftBrace node);
    void caseTRightBrace(TRightBrace node);
    void caseTLeftQuote(TLeftQuote node);
    void caseTRightQuote(TRightQuote node);
    void caseTDot(TDot node);
    void caseTComma(TComma node);
    void caseTSemi(TSemi node);
    void caseTIdentifier(TIdentifier node);
    void caseTIntNum(TIntNum node);
    void caseTMisc(TMisc node);
    void caseEOF(EOF node);
}
